import Foundation

/// Starting chosen containers at login, without the app.
///
/// `container run` has no restart policy — no `--restart always` — so nothing
/// in the runtime brings containers back. And now that the service itself is
/// started by launchd at login (see `ServiceAutostart`), there is no app around
/// to do it either. So a second agent does: it waits for the service, then
/// starts whatever is on the list.
///
/// The list lives in its own file rather than baked into the script, so
/// changing the selection rewrites one small file and leaves the agent alone.
enum ContainerAutostart {
    static let label = "com.containerdesktop.ContainerGUI.containers"

    static var supportDirectory: URL {
        URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent("Library/Application Support/ContainerDesktop")
    }

    static var scriptURL: URL { supportDirectory.appendingPathComponent("start-containers.sh") }
    static var listURL: URL { supportDirectory.appendingPathComponent("autostart-containers.txt") }

    static var agentURL: URL {
        URL(fileURLWithPath: NSHomeDirectory())
            .appendingPathComponent("Library/LaunchAgents/\(label).plist")
    }

    enum State: Equatable, Sendable {
        case off
        case on
        /// Something not ours already holds the name. Left alone.
        case foreign
    }

    // MARK: - The selection

    /// Drops ids that no longer exist, so a deleted container cannot haunt the
    /// list for ever. Order follows `existing`, so the file is stable.
    static func pruned(selected: Set<String>, existing: [String]) -> [String] {
        existing.filter(selected.contains)
    }

    static func listContents(_ ids: [String]) -> String {
        ids.isEmpty ? "" : ids.joined(separator: "\n") + "\n"
    }

    static func parseList(_ text: String) -> [String] {
        text.split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    // MARK: - The agent

    /// Waits for the service, then starts each listed container.
    ///
    /// The readiness test is anchored on purpose: `container system status`
    /// prints "apiserver is **not running**…" when it is down, so a plain
    /// search for "running" would match the failure and start nothing.
    static func script(binary: String, listPath: String) -> String {
        """
        #!/bin/sh
        # Generated by Container Desktop. Starts the containers listed in the
        # file below once the container service is up.
        BIN=\(shellQuote(binary))
        LIST=\(shellQuote(listPath))

        [ -f "$LIST" ] || exit 0

        # Up to two minutes: the service is started by its own agent at login
        # and takes a few seconds, but must never hang this script for ever.
        i=0
        until "$BIN" system status 2>/dev/null | grep -qE '^status[[:space:]]+running$'; do
            i=$((i + 1))
            [ "$i" -ge 60 ] && exit 1
            sleep 2
        done

        while IFS= read -r id; do
            [ -n "$id" ] && "$BIN" start "$id" >/dev/null 2>&1
        done < "$LIST"
        """
    }

    static func plist(scriptPath: String) -> [String: Any] {
        [
            "Label": label,
            "ProgramArguments": ["/bin/sh", scriptPath],
            "RunAtLoad": true,
        ]
    }

    static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    // MARK: - Installing

    static func state(agentExists: Bool, agentIsOurs: Bool) -> State {
        guard agentExists else { return .off }
        return agentIsOurs ? .on : .foreign
    }

    static func current(manager: FileManager = .default) -> State {
        guard manager.fileExists(atPath: agentURL.path) else { return .off }
        let data = (try? Data(contentsOf: agentURL)) ?? Data()
        let parsed = try? PropertyListSerialization.propertyList(from: data, format: nil)
        let arguments = (parsed as? [String: Any])?["ProgramArguments"] as? [String] ?? []
        return state(agentExists: true, agentIsOurs: arguments.contains(scriptURL.path))
    }

    static func writeList(_ ids: [String], manager: FileManager = .default) throws {
        try manager.createDirectory(at: supportDirectory, withIntermediateDirectories: true)
        try listContents(ids).write(to: listURL, atomically: true, encoding: .utf8)
    }

    static func enable(binary: String, manager: FileManager = .default) throws {
        try manager.createDirectory(at: supportDirectory, withIntermediateDirectories: true)
        try script(binary: binary, listPath: listURL.path)
            .write(to: scriptURL, atomically: true, encoding: .utf8)
        try manager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptURL.path)

        try manager.createDirectory(
            at: agentURL.deletingLastPathComponent(), withIntermediateDirectories: true
        )
        let data = try PropertyListSerialization.data(
            fromPropertyList: plist(scriptPath: scriptURL.path), format: .xml, options: 0
        )
        try data.write(to: agentURL)
    }

    static func disable(manager: FileManager = .default) throws {
        guard current(manager: manager) == .on else { return }
        try manager.removeItem(at: agentURL)
    }
}
