-- One row per installation, not per update check: the question this answers is
-- "how many people run Container Desktop, and on which version", so a check
-- overwrites the row it already has rather than appending a new one. That keeps
-- writes at one per install per day, far under D1's free tier (100k/day).
CREATE TABLE IF NOT EXISTS installs (
    id         TEXT PRIMARY KEY,   -- random UUID generated by the app, tied to nothing
    version    TEXT NOT NULL,
    os         TEXT,               -- macOS version, e.g. "27.0"
    first_seen TEXT NOT NULL,
    last_seen  TEXT NOT NULL,
    checks     INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS installs_last_seen ON installs (last_seen);
CREATE INDEX IF NOT EXISTS installs_version   ON installs (version);
